### ISSUE TITLE
Bugs | Language is not working on android

### ISSUE THREAD

**Issue by jacquesngomeheffa** [pawan-pk/react-native-mapbox-navigation#3]
Dear,
I greatly appreciate your work and the effort that goes with it.

Your package looks to work correctly but i have differents bugs, 
1 The navigation icon is behind the road stroke and also the roads names
2 My phone is in french, so the turn by turn instructions is read in english voice over.
![@pawan-pk react-native-mapbox-navigation bugs](https://github.com/user-attachments/assets/a7861637-6978-4753-8766-074c0c8e54e7)

3 not a bugs but a question, does your package support waypoints?

Thank you in advance, you are doing a great job.

**Comment by pawan-pk** [comment]
Thanks for your feedback.
Package is still in development mode, currently waypoints is not supported. I will provide waypoints support asap.

**Comment by pawan-pk** [comment]
> Dear, I greatly appreciate your work and the effort that goes with it.
> 
> Your package looks to work correctly but i have differents bugs, 
> 1. The navigation icon is behind the road stroke and also the roads names 
> 2. My phone is in french, so the turn by turn instructions is read in english voice over. 
> 3. not a bugs but a question, does your package support waypoints?
> 
> Thank you in advance, you are doing a great job.

Fixed in releases version ([v0.1.6](https://github.com/pawan-pk/react-native-mapbox-navigation/releases/tag/v0.1.6))
@jacquesngomeheffa, I appreciate your feedback and waypoint will added on next release.

**Comment by jacquesngomeheffa** [comment]
@pawan-pk Thank u

**Comment by jacquesngomeheffa** [comment]
@pawan-pk I have just tested the language, maybe i'm wrong but it's still the same. The Voice over (turn-by-turn Voice is still in English) is trying to speak out a french text.
And the instructions text on top of navigation is black on my phone 
![image](https://github.com/user-attachments/assets/4bc35ac6-6dc1-4434-8cd7-dd88bb0105a1)
But it looks to be white on yours
![image](https://github.com/user-attachments/assets/5b55ae14-25aa-408a-9749-672dc22b671d)

Thanks

**Comment by pawan-pk** [comment]
It seems like you are using your phone is in dark mode, the language config is not realtime you need to set parameter on initial render of navigation view, for debug reload app after adding language props.

**Comment by jacquesngomeheffa** [comment]
@pawan-pk  I tried it many times, but i still get the same result, not working on Android, and on iOS the first time is not working but the second time the instruction is translated.
This is how I integrated it (for testing) 
![image](https://github.com/user-attachments/assets/96bf03e1-ed6b-43a2-83b4-fecd318ab3c4)

**Comment by pawan-pk** [comment]
@jacquesngomeheffa, It appears to be a bug. We're reopening the issue and a fix will be provided shortly.

**Comment by jacquesngomeheffa** [comment]
Hi @pawan-pk 
I was wondering if it is  possible to also check if the language can adjust the Map labels, directions, and voice where possible. 

Also possible to set the default to be the devices locale? 

I'm also looking forward to your next release, which including the waypoints, 

Thanks for the great job.

**Comment by jacquesngomeheffa** [comment]
Hi @pawan-pk 

It looks like the language is working correctly now. I din't change anything.

**Comment by pawan-pk** [comment]
Closing issue as completed in ([release 0.1.8](https://github.com/pawan-pk/react-native-mapbox-navigation/releases/tag/v0.1.8))

**Comment by jacquesngomeheffa** [comment]
> It seems like you are using your phone is in dark mode, the language config is not realtime you need to set parameter on initial render of navigation view, for debug reload app after adding language props.


Dear @pawan-pk 
I still have this issue, The text is in black on my phone (despite being in dark or light mode) and yours looks to be White
![image](https://github.com/user-attachments/assets/73c68db7-7028-4e58-af28-9b199a063e33)

Great Job by Adding the Waypoints, I will be testing it the next days. I'm a big fan of your hard work, I'm very thankful

**Comment by pawan-pk** [comment]
Fixed text color day and night issue in release [Release 0.3.0](https://github.com/pawan-pk/react-native-mapbox-navigation/releases/tag/v0.3.0)

**Comment by jacquesngomeheffa** [comment]
@pawan-pk Thanks a lot,  it works now 🤩
